version: '3'
services:
  soma:
    container_name: soma
    build:
      context: ./
      dockerfile: ./dckr/Dockerfile
    image: chari8/soma
    ports:
      - "8000:8000"
    volumes:
      # mount ./ as /app
      - ./:/app
      # exclude volumens by over write
      - /app/node_modules
    tty: true
    stdin_open: true

